name: Building JAR with Maven

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
          tag_name: v1.0.0
          release_name: v1.0.0
          draft: false
          prerelease: false
    
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: target/springboot-0.0.1.jar
        asset_name: springboot-0.0.1.jar
        asset_content_type: application/java-archive
